on:
  pull_request:
    types:
      - labeled
jobs:
  slackNotificationLabel:
    if: ${{ github.event.label.name == 'two-reviewers' }}
    name: Slack Notification Label
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Slack Notification
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_CHANNEL: hackathon
          SLACK_MESSAGE: This Pull Request has two reviewers
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_HACKATHON_CHANNEL }}
